# Generated by Django 5.0.1 on 2024-02-03 23:31

import django.db.models.deletion
import polls.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.TextField(default=polls.helpers.nanoid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question_text', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.TextField(default=polls.helpers.nanoid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('choice_text', models.TextField()),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
